### ISSUE TITLE
Запуск не запускает...

### ISSUE THREAD

**Issue by kungermu** [MalikDeveloper2077/VKQuoteBot#1]
python3 bot.py:
Traceback (most recent call last):
  File "bot.py", line 4, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'
python bot.py:
  File "bot.py", line 64
    new_user_image_path = f'user_images/draw{random.randint(1, 9999999)}.png'
                                                                            ^
SyntaxError: invalid syntax

**Comment by kungermu** [comment]
Pillow ставиться только 6.2.2, 7.0.0 не видит, Debian 9.
